name: Waka Readme

on:
  schedule:
    # Runs daily at 12:30am IST (18:30 UTC)
    - cron: '30 18 * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow.

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
